import { assetUrl } from "@/lib/utils/asset-url";
import type { ShopProduct } from "./types";

/**
 * Mock fixture data — used when SHOPIFY_MODE=mock (Shopify store not yet live).
 * Same shape as live Storefront response so swap is mechanical.
 */
export const mockProducts: ShopProduct[] = [
  {
    id: "mock-1",
    handle: "scoutpaw-pack-poster",
    title: "ScoutPaw Pack Poster",
    description: "All five pups, ready to keep the pack company on your wall.",
    imageUrl: assetUrl("shop/promotion.jpg"),
    imageAlt: "ScoutPaw Pack poster featuring all five characters",
    price: { amount: "24.00", currencyCode: "USD" },
    onlineStoreUrl: "#mock-store",
    tags: ["New", "Home Goods"],
  },
  {
    id: "mock-2",
    handle: "max-plush-toy",
    title: "Max the Golden Plush",
    description: "Soft, snuggle-friendly plush of Max.",
    imageUrl: assetUrl("characters/golden-2.png"),
    imageAlt: "Max plush toy",
    price: { amount: "32.00", currencyCode: "USD" },
    onlineStoreUrl: "#mock-store",
    tags: ["Plush", "Bestseller"],
  },
  {
    id: "mock-3",
    handle: "rocky-husky-tee",
    title: "Rocky the Husky Tee",
    description: "Soft cotton tee featuring Rocky the Husky.",
    imageUrl: assetUrl("characters/husky-bg.png"),
    imageAlt: "Rocky the Husky tee",
    price: { amount: "28.00", currencyCode: "USD" },
    onlineStoreUrl: "#mock-store",
    tags: ["Apparel", "Adult"],
  },
  {
    id: "mock-4",
    handle: "the-pack-sticker-set",
    title: "The Pack Sticker Set",
    description: "Five vinyl stickers — one for every pup in the pack.",
    imageUrl: assetUrl("shop/promotion.jpg"),
    imageAlt: "ScoutPaw sticker set",
    price: { amount: "8.00", currencyCode: "USD" },
    onlineStoreUrl: "#mock-store",
    tags: ["Stationery", "Gift"],
  },
  {
    id: "mock-5",
    handle: "oscar-collie-plush",
    title: "Oscar the Collie Plush",
    description: "Oscar, ready for cuddles and long walks alike.",
    imageUrl: assetUrl("characters/collie-bg.png"),
    imageAlt: "Oscar plush toy",
    price: { amount: "32.00", currencyCode: "USD" },
    onlineStoreUrl: "#mock-store",
    tags: ["Plush"],
  },
  {
    id: "mock-6",
    handle: "buddy-corgi-tee-kid",
    title: "Buddy Corgi Kid's Tee",
    description: "Bright tee with Buddy the Corgi — sized for little humans.",
    imageUrl: assetUrl("characters/corgi-bg.png"),
    imageAlt: "Buddy the Corgi kids tee",
    price: { amount: "22.00", currencyCode: "USD" },
    onlineStoreUrl: "#mock-store",
    tags: ["Apparel", "Kids"],
  },
  {
    id: "mock-7",
    handle: "bella-poodle-mug",
    title: "Bella Poodle Mug",
    description: "Ceramic mug featuring Bella — just the way mornings should start.",
    imageUrl: assetUrl("characters/poodle-bg.png"),
    imageAlt: "Bella the Poodle mug",
    price: { amount: "18.00", currencyCode: "USD" },
    onlineStoreUrl: "#mock-store",
    tags: ["Home Goods", "New"],
  },
  {
    id: "mock-8",
    handle: "scoutpaw-tote",
    title: "ScoutPaw Daily Tote",
    description: "Heavy-duty canvas tote, perfect for park days and grocery runs.",
    imageUrl: assetUrl("shop/promotion.jpg"),
    imageAlt: "ScoutPaw canvas tote",
    price: { amount: "26.00", currencyCode: "USD" },
    onlineStoreUrl: "#mock-store",
    tags: ["Bag", "Adult"],
  },
];
